---
title: "Using Tidy Models to Do Linear Regression Modelling"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidymodels)
library(tidyverse)
tidymodels_prefer()
```


```{r}
#Import Data
data(ames)

#Spending Data Allocation for Modelling
set.seed(123)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test <- testing(ames_split)

#Recipe Creation for Tidy Models
simple_rec <-
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type, data = ames_train)

# Creating Linear Regression Model Engine
lm_model <-
  linear_reg() %>%
  set_engine("lm")

# Creating Workflow for Tidy Models
lm_wflow <-
  workflow() %>%
  add_variables(outcome = Sale_Price, predictors = c(Longitude, Latitude))%>%
  add_model(lm_model)

lm_wflow <-
  lm_wflow %>%
  remove_variables() %>%
  add_recipe(simple_rec)

# Fitting the Linear Regression to the Data
lm_fit <- fit(lm_wflow, ames_train)

# Tidying the Fitted Data
lm_fit %>%
  extract_fit_parsnip() %>%
  tidy()

# Bringing the Model back into Base R to use Base R functions on the Model
lm_fit_var <- lm_fit %>% extract_fit_engine()

summary(lm_fit_var)
plot(lm_fit_var)
```

```{r}
# ames_test_res <- predict(lm_fit, new_data = ames_test %>% select(-Sale_Price))
# ames_test_res
# 
# ames_test_res <- bind_cols(ames_test_res, ames_test %>% select(Sale_Price))
# ames_test_res
# 
# ggplot(ames_test_res, aes(x = Sale_Price, y = .pred)) +
#   geom_abline(lty = 2) +
#   geom_point(alpha = 0.5) +
#   labs(y = "Predicted Sale Price (log10)", x = "Sale Price (log10)") +
#   coord_obs_pred()

#This sets a function for Metric Sets and Assigns it to ames_metrics
#ames_metrics is then called with the df, truth, and estimate to output the tibble.
# ames_metrics <- metric_set(rmse, rsq, mae)
# ames_metrics(ames_test_res, truth = Sale_Price, estimate = .pred)
```
