---
title: "ST516 HW8"
author: "Keenan Smith"
date: "3/9/2022"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(parameters)
```

```{r}
model_analysis <- function(model) {
  summary(model)
  plot(model)
  visreg::visreg(model)
  parameters::model_parameters(model)
  performance::check_model(model)
  performance::check_collinearity(model)
}
```


```{r Problem 2, include=FALSE}
movies <- read_csv("movies.csv", show_col_types = FALSE)
movies <-
  movies %>%
  rename(movie = Movie,
         gross = `USGross($)`,
         budget = `Budget($)`,
         stars = Stars,
         rating = Rating,
         genre = Genre,
         run_time = `Run Time (minutes)`) %>%
  mutate(rating = as.factor(rating),
         genre = as.factor(genre))

movies_r_pg13 <-
  movies %>%
  filter(rating == "PG-13" | rating == "R")

movies_model <- lm(gross ~ budget * rating, data = movies_r_pg13)
summary(movies_model)
plot(movies_model)

movies_r_nkk <- movies_r_pg13[-90,]

movies_model_adj <- lm(gross ~ budget * rating, data = movies_r_nkk)

summary(movies_model_adj)
plot(movies_model_adj)

r_1 <- tibble(budget = 0, rating = as.factor("R"))
r_2 <- tibble(budget = 1, rating = as.factor("R"))
r1_score <- predict(movies_model_adj, newdata = r_1)
r2_score <- predict(movies_model_adj, newdata = r_2)

r_difference <- r2_score - r1_score
r_difference
```

## Problem #4
```{r Problem 4}
# Import Data Step
dirt_bike <- read_csv("dirt_bikes.csv", show_col_types = FALSE)
# Tidy and Modify Data Step w/o categorical engine stroke
dirt_bike <-
  dirt_bike %>%
  rename(model = Model,
         manufacturer = Manufacturer,
         color = Color,
         msrp = MSRP,
         engine_stroke = `Engine Stroke`,
         displacement = Displacement,
         bore = Bore,
         wheelbase = Wheelbase,
         clearance = Clearance,
         total_weight = `Total Weight`) %>%
  mutate(manufacturer = as.factor(manufacturer),
         color = as.factor(color)) %>%
  arrange(desc(engine_stroke))

# Create Dataframe for categorical engine stroke
dirt_bike_mod <-
  dirt_bike %>%
  mutate(engine_stroke = as.factor(engine_stroke))

# Model for Non-categorical Engine Stroke
model_dirt_bike <- lm(msrp ~ bore + clearance + engine_stroke + total_weight + wheelbase, data = dirt_bike)
summary(model_dirt_bike)
# visreg::visreg(model_dirt_bike)
plot(model_dirt_bike)

# Model for Adding Displacement
model_dirt_disp <- lm(msrp ~ bore + clearance + engine_stroke + total_weight + wheelbase + displacement, data = dirt_bike)
summary(model_dirt_disp)
# visreg::visreg(model_dirt_disp)
plot(model_dirt_disp)
anova(model_dirt_disp)

# Calculating VIF for the Displacement Model
car::vif(model_dirt_disp)
car::vif(model_dirt_bike_factor)
# Model for Categorical Engine Stroke
model_dirt_bike_factor <- lm(msrp ~ bore + clearance + engine_stroke + total_weight + wheelbase, data = dirt_bike_mod)
summary(model_dirt_bike_factor)
visreg::visreg(model_dirt_bike_factor)

```

