---
title: "Cleaning US Census Data"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries
library(readr)
library(dplyr)
library(tidyr)
```

```{r message=FALSE, warning=FALSE, error=TRUE}
# load CSVs
files <- list.files(pattern = "states_.*csv" )
df_list <- lapply(files, read_csv)
```

```{r error=TRUE}
# inspect data
us_census <- bind_rows(df_list)
# head(us_census)
# colnames(us_census)
# str(us_census)

```

```{r error=TRUE}
# remove % from race columns
us_census <- us_census %>%
  select(-X1) %>%
  mutate(Hispanic=gsub('\\%','',Hispanic),
         White=gsub('\\%','',White),
         Black=gsub('\\%','',Black),
         Native=gsub('\\%','',Native),
         Asian=gsub('\\%','',Asian),
         Pacific=gsub('\\%','',Pacific),
         Income=gsub('\\$','',Income)) %>%
  separate(GenderPop, c('male_pop', 'female_pop'), '_') %>%
  mutate(male_pop=gsub('M','',male_pop),
         female_pop=gsub('F','',female_pop)) %>%
  mutate(Hispanic = as.numeric(Hispanic),
         White = as.numeric(White),
         Black = as.numeric(Black),
         Native = as.numeric(Native),
         Asian = as.numeric(Asian),
         Pacific = as.numeric(Pacific),
         Income = as.numeric(Income),
         male_pop = as.numeric(male_pop),
         female_pop = as.numeric(female_pop)) %>%
  mutate(Hispanic = Hispanic/100,
         White = White/100,
         Black = Black/100,
         Native = Native/100,
         Asian = Asian/100,
         Pacific = Pacific/100) %>%
   distinct()

head(us_census)

```

---
title: "Cleaning US Census Data"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries
library(readr)
library(dplyr)
library(tidyr)
```

```{r message=FALSE, warning=FALSE, error=TRUE}
# load CSVs
files <- list.files(pattern = "states_.*csv" )
df_list <- lapply(files, read_csv)
```

```{r error=TRUE}
# inspect data
us_census <- bind_rows(df_list)
# head(us_census)
# colnames(us_census)
# str(us_census)

```

```{r error=TRUE}
# remove % from race columns
us_census <- us_census %>%
  select(-X1) %>%
  mutate(Hispanic=gsub('\\%','',Hispanic),
         White=gsub('\\%','',White),
         Black=gsub('\\%','',Black),
         Native=gsub('\\%','',Native),
         Asian=gsub('\\%','',Asian),
         Pacific=gsub('\\%','',Pacific),
         Income=gsub('\\$','',Income)) %>%
  separate(GenderPop, c('male_pop', 'female_pop'), '_') %>%
  mutate(male_pop=gsub('M','',male_pop),
         female_pop=gsub('F','',female_pop)) %>%
  mutate(Hispanic = as.numeric(Hispanic),
         White = as.numeric(White),
         Black = as.numeric(Black),
         Native = as.numeric(Native),
         Asian = as.numeric(Asian),
         Pacific = as.numeric(Pacific),
         Income = as.numeric(Income),
         male_pop = as.numeric(male_pop),
         female_pop = as.numeric(female_pop)) %>%
  mutate(Hispanic = Hispanic/100,
         White = White/100,
         Black = Black/100,
         Native = Native/100,
         Asian = Asian/100,
         Pacific = Pacific/100) %>%
   distinct()

head(us_census)

```
